name: "Build Chrome"
on:
  workflow_dispatch:
  
jobs:
  build_chrome:
    name: "Build Chrome"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: TickBack-${{ github.run_number }}
          path: src_chrome/